##################   Автоматика
title: Вся автоматика
icon: mdi:script
cards:
    
      - type: vertical-stack
        cards:
        
          - type: markdown
            content: >
                **Автоматизации**

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: automation
                 options:
                    secondary_info: last-triggered
                 sort:
                   method: name
            exclude:
               - state: 'off'


          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: automation
                 options:
                    secondary_info: last-triggered
                 sort:
                   method: name
              exclude:
               - state: 'on'

               
      - type: vertical-stack
        cards:
        
          - type: markdown
            content: >
                **Скрипты**

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: script
                 options:
                    secondary_info: last-triggered
                 sort:
                   method: attribute
                   attribute: last_triggered
                   reverse: true
              sort:
                 method: entity_id  
               
      - type: vertical-stack
        cards:
        
          - type: markdown
            content: >
                **Группы**

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: group
                 sort:
                    method: name