homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Kiev
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password
  
  whitelist_external_dirs :
   - /config
   - /config/bash

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

system_health:

# Stream component for camera
stream:

lovelace:
  mode: yaml

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

#Платформы
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 380

mqtt:
  broker: core-mosquitto
  username: mqtt
  password: mqtt

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key
#   mode: daily

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

remote:
  - platform: xiaomi_miio
    name: "kitchen remote"
    host: 192.168.0.135
    token: db472a45b4f1913439abaab3f7ff6356
    slot: 3
    timeout: 30
    hidden: false

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: F0:B4:29:CC:1F:11
      key: !secret gateway1_api
      host: 192.168.0.80
    - mac: 28:6C:07:F0:AD:27
      key: !secret gateway2_api
      host: 192.168.0.81
    - mac: 34:CE:00:88:B0:39
      key: !secret gateway3_api
      host: 192.168.0.82
    - mac: 78:11:DC:64:F4:C8
      key: !secret gateway4_api
      host: 192.168.0.83

telegram_bot:
  - platform: polling
    api_key: !secret api_key_70
    allowed_chat_ids:
      - !secret chat_id_alex
      - !secret chat_id_olha
      
# Кастомные карты
hacs:
  token: !secret HACS_github
  appdaemon: true
  python_script: true
  theme: true

# Роутер
asuswrt:
  host: !secret asus_ip
  username: !secret asus_user
  password: !secret asus_password
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

device_tracker:
  - platform: asuswrt
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  
#Вынос в папки
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/bin_sensor
automation: !include_dir_merge_list includes/automation
switch: !include_dir_merge_list includes/switches
script: !include_dir_merge_named includes/scripts

#Вынос в файлы
plant: !include includes/plants.yaml
input_number: !include includes/input_number.yaml
media_player: !include includes/mplayer.yaml
light: !include includes/light.yaml
yeelight: !include includes/yeelight.yaml
camera: !include includes/camera.yaml
timer: !include includes/timer.yaml
counter: !include includes/counter.yaml
fan: !include includes/fan.yaml
recorder: !include includes/recorder.yaml 
group: !include includes/groups.yaml
rest_command: !include includes/rest_command.yaml
notify: !include includes/notify.yaml
